language: cpp

before_install:
  - sudo apt-get install boost-all-dev
  - sudo apt-get install cmake
compiler:
  - gcc
script:
  - mkdir Debug
  - cd Debug
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make
  - make test
